version: 0.01
src_es:
  host: 127.0.0.1
  index: my-index
  trace: true
  port: 9200
target_es:
  host: 127.0.0.1
  index: my-index-v2
  trace: true
  port: 9200
others:
    rebuild: false
    batch: 2000
    where:
